version: '3.8'
services:
  ##
  ## UI Tests
  ##
  testui:
    image: ${IMAGE_TAG:-edeliverytest}/${IMAGE_SMP_TESTS}:${SMP_VERSION}
    environment:
      - TEST_PLAN=api
      - TEST_URL=http://smp-springboot-mysql.local:8084/smp/
    networks:
      - test-network
networks:
  test-network:
    external:
      name: ${DOCKER_NETWORK_NAME:-domismp-springboot-mysql_default}
